---
sidebar: sidebar_aws
permalink: aws/reference_whats_new_cloud_volumes_aws.html
keywords: Cloud Volumes Service for AWS, what's new, features, enhancements
summary: NetApp periodically updates Cloud Volumes Service for AWS to bring you new features and enhancements.
---

= What's new in Cloud Volumes Service for AWS
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
NetApp periodically updates Cloud Volumes Service for AWS to bring you new features and enhancements.

== February 2020
* The NetApp Cloud Volumes Service is now available as a Metered (pay as you go) subscription in the AWS Marketplace. See the Marketplace listing for more details at: https://aws.amazon.com/marketplace/pp/B0848MXK74
Note that the original monthly and annual subscription plans are still available.

== January 2020
* Cloud Volumes Service now supports SMB multichannel which uses multiple network connections simultaneously to provide increased performance. Multichannel is enabled by default on Windows clients, but requires that the EC2 instance uses a network adapter that support RSS (Receive Side Scaling).
* Reverting a volume from a snapshot is now available from the Cloud Volumes Service user interface. This enables you to revert volumes to a point in time snapshot without requiring clients to remount. See link:task_reverting_volume_to_snapshot.html[Reverting a volume from a snapshot] for details.

== December 2019
* Cloud Volumes Service now supports NFSv4.1 in addition to NFSv3 and SMB. A volume can be exported over any or all of the supported protocols. NFSv4.1 is a stateful protocol and provides improved file locking, ACLs for better compatibility between Linux and Windows, and many other improvements.
* Cloud Volumes can be configured so that the .snapshot directory (previous version in Windows) can be hidden or shown.
* An Overview page is now available per volume that displays QoS settings, data usage, and performance information such as bandwidth, IOPS, and latency.

== September 2019
* Cloud Volumes Service now supports up to 100 million files per volume. The maximum file count is increased by 20 million for each Terabyte allocated up to 100 million. The maximum may be increased to higher than 100 million via a customer support request.
* Cloud volume names now support up to 253 characters; an increase from the previous limit of 64 characters.
*	The user interface now displays the service level per volume in the volume list page.

== August 2019
* Cloud Volumes Service now provides up to 4,500 MB/s, instead of 3,500 MB/s, at certain capacity levels. See link:reference_selecting_service_level_and_quota.html#cost-comparison-for-service-levels-and-allocated-capacity[Selecting the service level and the allocated capacity] for details.
* Added API examples and sample Python scripts for Active Directory functions (link:reference_cloud_volume_apis.html[Cloud Volumes APIs]).

== July 2019
* Creating a volume from a snapshot is now rapid, and the volume is available within seconds regardless of the amount of data in the parent volume.
* The user interface now displays the used capacity per volume.
* The API has been updated to report used capacity, and total inodes and used inodes.
* The API has been updated to use the same service levels names as the user interface (Standard, Premium, and Extreme).
* The sample Python scripts have been updated to match the updated APIs.

== March 2019
* Added support for Microsoft Active Directory in the AWS Cloud (AWS Managed Microsoft AD) for SMB cloud volumes.
* The control plane for us-east-1 and us-west-1 now have their own UI URL and API endpoint. Previously these regions shared the same control plane.
* Sample Python scripts have been added for RESTful API support: link:reference_cloud_volume_apis.html[Cloud Volumes APIs]

== February 2019
* Beta release of Cloud Backup Service for US-WEST-2: link:reference_cloud_backup_service_intro.html[Managing backups using Cloud Backup Service (beta for US-WEST-2)]

== January 2019
* NetApp Cloud Volumes Service is now publicly available on the https://aws.amazon.com/marketplace/pp/B07MF4GHYW?qid=1548352732912&sr=0-1&ref_=srh_res_product_title[AWS Marketplace^]
* Access from on-prem clients is now supported via AWS Direct Connect and Virtual Private Gateways
* A service status webpage is now available at https://status.services.cloud.netapp.com/ so you can verify availability of the CVS service in each supported region
