---
sidebar: sidebar_aws
permalink: aws/reference_known_issues.html
keywords: Cloud Volumes Service for AWS limitations and known issues
summary: The following known issues and limitations exist in Cloud Volumes Service for AWS.
---

= Known Issues and limitations
:toc: macro
:hardbreaks:
:nofooter:
:icons: font
:linkattrs:
:imagesdir: ./media/

[.lead]
The following known issues and limitations exist in Cloud Volumes Service for AWS.

* *Issue*: Creating a new volume from a snapshot may fail with the message 'Unable to set volume attribute "files" for volume _<volume>_ …​ Reason: New count must be larger than current allocated count of _<number>_'.
+
*Workaround*: This issue occurs when trying to create a volume from a snapshot that currently has more files allocated to it than the new volume would be assigned for its allocated capacity. You must increase the allocated capacity for the new volume to assign enough files (inodes). See link:reference_selecting_service_level_and_quota.html#allocated-capacity[Selecting the allocated capacity] for details.

* *Issue*: Users with expired subscriptions cannot log in to the Cloud Volumes Service user interface or interact with the API.
+
*Workaround*: Go to the AWS Marketplace page for the Cloud Volumes Service and renew your subscription.
